export const jobArray = [
  {
    jobTitle: "Software Engineer",
    companyName: "Google",
    companyLogo: "",
    location: "Mountain View, CA",
    salaryRange: "12LPA",
    jobType: "Full Time",
    jobDescription: "",
    workMode: "Onsite",
  },
  {
    jobTitle: "Software Engineer",
    companyName: "Google",
    companyLogo: "",
    location: "Mountain View, CA",
    salaryRange: "12LPA",
    jobType: "Full Time",
    jobDescription: "",
    workMode: "Onsite",
  },
  {
    jobTitle: "Software Engineer",
    companyName: "Google",
    companyLogo: "",
    location: "Mountain View, CA",
    salaryRange: "12LPA",
    jobType: "Full Time",
    jobDescription: "",
    workMode: "Onsite",
  },
  {
    jobTitle: "Software Engineer",
    companyName: "Google",
    companyLogo: "",
    location: "Mountain View, CA",
    salaryRange: "12LPA",
    jobType: "Full Time",
    jobDescription: "",
    workMode: "Onsite",
  },
  {
    jobTitle: "Software Engineer",
    companyName: "Google",
    companyLogo: "",
    location: "Mountain View, CA",
    salaryRange: "12LPA",
    jobType: "Full Time",
    jobDescription: "",
    workMode: "Onsite",
  },
  {
    jobTitle: "Software Engineer",
    companyName: "Google",
    companyLogo: "",
    location: "Mountain View, CA",
    salaryRange: "12LPA",
    jobType: "Full Time",
    jobDescription: "",
    workMode: "Onsite",
  },
  {
    jobTitle: "Software Engineer",
    companyName: "Google",
    companyLogo: "",
    location: "Mountain View, CA",
    salaryRange: "12LPA",
    jobType: "Full Time",
    jobDescription: "",
    workMode: "Onsite",
  },
  {
    jobTitle: "Software Engineer",
    companyName: "Google",
    companyLogo: "",
    location: "Mountain View, CA",
    salaryRange: "12LPA",
    jobType: "Full Time",
    jobDescription: "",
    workMode: "Onsite",
  },
  {
    jobTitle: "Software Engineer",
    companyName: "Google",
    companyLogo: "",
    location: "Mountain View, CA",
    salaryRange: "12LPA",
    jobType: "Full Time",
    jobDescription: "",
    workMode: "Onsite",
  },
  {
    jobTitle: "Software Engineer",
    companyName: "Google",
    companyLogo: "",
    location: "Mountain View, CA",
    salaryRange: "12LPA",
    jobType: "Full Time",
    jobDescription: "",
    workMode: "Onsite",
  },
];
